# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a814a503628fc24bbe5ade9202b8771cdb24d8095f0a2e8050ccc4a5fed09a07aeb52ce52c55bdc81a81cd300f9a30f61161c3bcbda8df73c2d34a7461bae73

test:
  secret_key_base: 5e02b1ea0afa885302481d226f90f417c219ec071e1530bdc258ab45bc5f64b380d4151bcf4f1bddd8e62f0c1e40e00950f900580554ab1f8e08d2b5b4ca2d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
